# Generated by Django 4.2.20 on 2025-03-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_datapoint_end_year_datapoint_pestle_datapoint_sector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='topics',
            new_name='topic',
        ),
    ]
